package com.proyecto.clientes.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.proyecto.clientes.model.Cliente;
import com.proyecto.clientes.service.ClienteLocalServiceUtil;

/**
 * The extended model base implementation for the Cliente service. Represents a row in the &quot;RES_CLIENTE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClienteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClienteImpl
 * @see com.proyecto.clientes.model.Cliente
 * @generated
 */
public abstract class ClienteBaseImpl extends ClienteModelImpl
    implements Cliente {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a cliente model instance should use the {@link Cliente} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ClienteLocalServiceUtil.addCliente(this);
        } else {
            ClienteLocalServiceUtil.updateCliente(this);
        }
    }
}
