package com.proyecto.citas.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.proyecto.citas.model.Cita;
import com.proyecto.citas.service.CitaLocalServiceUtil;

/**
 * The extended model base implementation for the Cita service. Represents a row in the &quot;RES_CITA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CitaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CitaImpl
 * @see com.proyecto.citas.model.Cita
 * @generated
 */
public abstract class CitaBaseImpl extends CitaModelImpl implements Cita {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a cita model instance should use the {@link Cita} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CitaLocalServiceUtil.addCita(this);
        } else {
            CitaLocalServiceUtil.updateCita(this);
        }
    }
}
