package com.proyecto.citas.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.proyecto.citas.model.DiaFestivo;
import com.proyecto.citas.service.DiaFestivoLocalServiceUtil;

/**
 * The extended model base implementation for the DiaFestivo service. Represents a row in the &quot;RES_DIA_FESTIVO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DiaFestivoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiaFestivoImpl
 * @see com.proyecto.citas.model.DiaFestivo
 * @generated
 */
public abstract class DiaFestivoBaseImpl extends DiaFestivoModelImpl
    implements DiaFestivo {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a dia festivo model instance should use the {@link DiaFestivo} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DiaFestivoLocalServiceUtil.addDiaFestivo(this);
        } else {
            DiaFestivoLocalServiceUtil.updateDiaFestivo(this);
        }
    }
}
