package com.proyecto.citas.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.proyecto.citas.model.DiaLibre;
import com.proyecto.citas.service.DiaLibreLocalServiceUtil;

/**
 * The extended model base implementation for the DiaLibre service. Represents a row in the &quot;RES_DIA_LIBRE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DiaLibreImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiaLibreImpl
 * @see com.proyecto.citas.model.DiaLibre
 * @generated
 */
public abstract class DiaLibreBaseImpl extends DiaLibreModelImpl
    implements DiaLibre {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a dia libre model instance should use the {@link DiaLibre} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DiaLibreLocalServiceUtil.addDiaLibre(this);
        } else {
            DiaLibreLocalServiceUtil.updateDiaLibre(this);
        }
    }
}
