package com.proyecto.citas.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.proyecto.citas.model.DiasLibres;
import com.proyecto.citas.service.DiasLibresLocalServiceUtil;

/**
 * The extended model base implementation for the DiasLibres service. Represents a row in the &quot;RES_DIAS_LIBRES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DiasLibresImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiasLibresImpl
 * @see com.proyecto.citas.model.DiasLibres
 * @generated
 */
public abstract class DiasLibresBaseImpl extends DiasLibresModelImpl
    implements DiasLibres {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a dias libres model instance should use the {@link DiasLibres} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DiasLibresLocalServiceUtil.addDiasLibres(this);
        } else {
            DiasLibresLocalServiceUtil.updateDiasLibres(this);
        }
    }
}
