package com.proyecto.citas.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.proyecto.citas.model.DiasFestivos;
import com.proyecto.citas.service.DiasFestivosLocalServiceUtil;

/**
 * The extended model base implementation for the DiasFestivos service. Represents a row in the &quot;RES_DIAS_FESTIVOS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DiasFestivosImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiasFestivosImpl
 * @see com.proyecto.citas.model.DiasFestivos
 * @generated
 */
public abstract class DiasFestivosBaseImpl extends DiasFestivosModelImpl
    implements DiasFestivos {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a dias festivos model instance should use the {@link DiasFestivos} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DiasFestivosLocalServiceUtil.addDiasFestivos(this);
        } else {
            DiasFestivosLocalServiceUtil.updateDiasFestivos(this);
        }
    }
}
