package com.proyecto.citas.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.proyecto.citas.model.HorarioTrabajo;
import com.proyecto.citas.model.HorarioTrabajoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the HorarioTrabajo service. Represents a row in the &quot;RES_HORARIO_TRABAJO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.proyecto.citas.model.HorarioTrabajoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HorarioTrabajoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HorarioTrabajoImpl
 * @see com.proyecto.citas.model.HorarioTrabajo
 * @see com.proyecto.citas.model.HorarioTrabajoModel
 * @generated
 */
public class HorarioTrabajoModelImpl extends BaseModelImpl<HorarioTrabajo>
    implements HorarioTrabajoModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a horario trabajo model instance should use the {@link com.proyecto.citas.model.HorarioTrabajo} interface instead.
     */
    public static final String TABLE_NAME = "RES_HORARIO_TRABAJO";
    public static final Object[][] TABLE_COLUMNS = {
            { "ID_HORARIO", Types.INTEGER },
            { "T_HORA_INICIO", Types.VARCHAR },
            { "T_HORA_FIN", Types.VARCHAR },
            { "T_HORA_INICIO_TARDE", Types.VARCHAR },
            { "T_HORA_FIN_TARDE", Types.VARCHAR },
            { "N_DURACION_CITAS", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table RES_HORARIO_TRABAJO (ID_HORARIO INTEGER not null primary key,T_HORA_INICIO VARCHAR(75) null,T_HORA_FIN VARCHAR(75) null,T_HORA_INICIO_TARDE VARCHAR(75) null,T_HORA_FIN_TARDE VARCHAR(75) null,N_DURACION_CITAS INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table RES_HORARIO_TRABAJO";
    public static final String ORDER_BY_JPQL = " ORDER BY horarioTrabajo.idHorario ASC";
    public static final String ORDER_BY_SQL = " ORDER BY RES_HORARIO_TRABAJO.ID_HORARIO ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.proyecto.citas.model.HorarioTrabajo"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.proyecto.citas.model.HorarioTrabajo"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.proyecto.citas.model.HorarioTrabajo"));
    private static ClassLoader _classLoader = HorarioTrabajo.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            HorarioTrabajo.class
        };
    private int _idHorario;
    private String _horaInicio;
    private String _horaFin;
    private String _horaInicioTarde;
    private String _horaFinTarde;
    private int _duracionCitas;
    private HorarioTrabajo _escapedModel;

    public HorarioTrabajoModelImpl() {
    }

    @Override
    public int getPrimaryKey() {
        return _idHorario;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setIdHorario(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _idHorario;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return HorarioTrabajo.class;
    }

    @Override
    public String getModelClassName() {
        return HorarioTrabajo.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("idHorario", getIdHorario());
        attributes.put("horaInicio", getHoraInicio());
        attributes.put("horaFin", getHoraFin());
        attributes.put("horaInicioTarde", getHoraInicioTarde());
        attributes.put("horaFinTarde", getHoraFinTarde());
        attributes.put("duracionCitas", getDuracionCitas());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer idHorario = (Integer) attributes.get("idHorario");

        if (idHorario != null) {
            setIdHorario(idHorario);
        }

        String horaInicio = (String) attributes.get("horaInicio");

        if (horaInicio != null) {
            setHoraInicio(horaInicio);
        }

        String horaFin = (String) attributes.get("horaFin");

        if (horaFin != null) {
            setHoraFin(horaFin);
        }

        String horaInicioTarde = (String) attributes.get("horaInicioTarde");

        if (horaInicioTarde != null) {
            setHoraInicioTarde(horaInicioTarde);
        }

        String horaFinTarde = (String) attributes.get("horaFinTarde");

        if (horaFinTarde != null) {
            setHoraFinTarde(horaFinTarde);
        }

        Integer duracionCitas = (Integer) attributes.get("duracionCitas");

        if (duracionCitas != null) {
            setDuracionCitas(duracionCitas);
        }
    }

    @Override
    public int getIdHorario() {
        return _idHorario;
    }

    @Override
    public void setIdHorario(int idHorario) {
        _idHorario = idHorario;
    }

    @Override
    public String getHoraInicio() {
        if (_horaInicio == null) {
            return StringPool.BLANK;
        } else {
            return _horaInicio;
        }
    }

    @Override
    public void setHoraInicio(String horaInicio) {
        _horaInicio = horaInicio;
    }

    @Override
    public String getHoraFin() {
        if (_horaFin == null) {
            return StringPool.BLANK;
        } else {
            return _horaFin;
        }
    }

    @Override
    public void setHoraFin(String horaFin) {
        _horaFin = horaFin;
    }

    @Override
    public String getHoraInicioTarde() {
        if (_horaInicioTarde == null) {
            return StringPool.BLANK;
        } else {
            return _horaInicioTarde;
        }
    }

    @Override
    public void setHoraInicioTarde(String horaInicioTarde) {
        _horaInicioTarde = horaInicioTarde;
    }

    @Override
    public String getHoraFinTarde() {
        if (_horaFinTarde == null) {
            return StringPool.BLANK;
        } else {
            return _horaFinTarde;
        }
    }

    @Override
    public void setHoraFinTarde(String horaFinTarde) {
        _horaFinTarde = horaFinTarde;
    }

    @Override
    public int getDuracionCitas() {
        return _duracionCitas;
    }

    @Override
    public void setDuracionCitas(int duracionCitas) {
        _duracionCitas = duracionCitas;
    }

    @Override
    public HorarioTrabajo toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (HorarioTrabajo) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        HorarioTrabajoImpl horarioTrabajoImpl = new HorarioTrabajoImpl();

        horarioTrabajoImpl.setIdHorario(getIdHorario());
        horarioTrabajoImpl.setHoraInicio(getHoraInicio());
        horarioTrabajoImpl.setHoraFin(getHoraFin());
        horarioTrabajoImpl.setHoraInicioTarde(getHoraInicioTarde());
        horarioTrabajoImpl.setHoraFinTarde(getHoraFinTarde());
        horarioTrabajoImpl.setDuracionCitas(getDuracionCitas());

        horarioTrabajoImpl.resetOriginalValues();

        return horarioTrabajoImpl;
    }

    @Override
    public int compareTo(HorarioTrabajo horarioTrabajo) {
        int primaryKey = horarioTrabajo.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof HorarioTrabajo)) {
            return false;
        }

        HorarioTrabajo horarioTrabajo = (HorarioTrabajo) obj;

        int primaryKey = horarioTrabajo.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<HorarioTrabajo> toCacheModel() {
        HorarioTrabajoCacheModel horarioTrabajoCacheModel = new HorarioTrabajoCacheModel();

        horarioTrabajoCacheModel.idHorario = getIdHorario();

        horarioTrabajoCacheModel.horaInicio = getHoraInicio();

        String horaInicio = horarioTrabajoCacheModel.horaInicio;

        if ((horaInicio != null) && (horaInicio.length() == 0)) {
            horarioTrabajoCacheModel.horaInicio = null;
        }

        horarioTrabajoCacheModel.horaFin = getHoraFin();

        String horaFin = horarioTrabajoCacheModel.horaFin;

        if ((horaFin != null) && (horaFin.length() == 0)) {
            horarioTrabajoCacheModel.horaFin = null;
        }

        horarioTrabajoCacheModel.horaInicioTarde = getHoraInicioTarde();

        String horaInicioTarde = horarioTrabajoCacheModel.horaInicioTarde;

        if ((horaInicioTarde != null) && (horaInicioTarde.length() == 0)) {
            horarioTrabajoCacheModel.horaInicioTarde = null;
        }

        horarioTrabajoCacheModel.horaFinTarde = getHoraFinTarde();

        String horaFinTarde = horarioTrabajoCacheModel.horaFinTarde;

        if ((horaFinTarde != null) && (horaFinTarde.length() == 0)) {
            horarioTrabajoCacheModel.horaFinTarde = null;
        }

        horarioTrabajoCacheModel.duracionCitas = getDuracionCitas();

        return horarioTrabajoCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(13);

        sb.append("{idHorario=");
        sb.append(getIdHorario());
        sb.append(", horaInicio=");
        sb.append(getHoraInicio());
        sb.append(", horaFin=");
        sb.append(getHoraFin());
        sb.append(", horaInicioTarde=");
        sb.append(getHoraInicioTarde());
        sb.append(", horaFinTarde=");
        sb.append(getHoraFinTarde());
        sb.append(", duracionCitas=");
        sb.append(getDuracionCitas());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(22);

        sb.append("<model><model-name>");
        sb.append("com.proyecto.citas.model.HorarioTrabajo");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>idHorario</column-name><column-value><![CDATA[");
        sb.append(getIdHorario());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>horaInicio</column-name><column-value><![CDATA[");
        sb.append(getHoraInicio());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>horaFin</column-name><column-value><![CDATA[");
        sb.append(getHoraFin());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>horaInicioTarde</column-name><column-value><![CDATA[");
        sb.append(getHoraInicioTarde());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>horaFinTarde</column-name><column-value><![CDATA[");
        sb.append(getHoraFinTarde());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>duracionCitas</column-name><column-value><![CDATA[");
        sb.append(getDuracionCitas());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
