package com.proyecto.citas.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.proyecto.citas.model.HorarioTrabajo;
import com.proyecto.citas.service.HorarioTrabajoLocalServiceUtil;

/**
 * The extended model base implementation for the HorarioTrabajo service. Represents a row in the &quot;RES_HORARIO_TRABAJO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HorarioTrabajoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HorarioTrabajoImpl
 * @see com.proyecto.citas.model.HorarioTrabajo
 * @generated
 */
public abstract class HorarioTrabajoBaseImpl extends HorarioTrabajoModelImpl
    implements HorarioTrabajo {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a horario trabajo model instance should use the {@link HorarioTrabajo} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            HorarioTrabajoLocalServiceUtil.addHorarioTrabajo(this);
        } else {
            HorarioTrabajoLocalServiceUtil.updateHorarioTrabajo(this);
        }
    }
}
