package com.proyecto.clientes.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Cliente service. Represents a row in the &quot;RES_CLIENTE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.proyecto.clientes.model.impl.ClienteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.proyecto.clientes.model.impl.ClienteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Cliente
 * @see com.proyecto.clientes.model.impl.ClienteImpl
 * @see com.proyecto.clientes.model.impl.ClienteModelImpl
 * @generated
 */
public interface ClienteModel extends BaseModel<Cliente> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a cliente model instance should use the {@link Cliente} interface instead.
     */

    /**
     * Returns the primary key of this cliente.
     *
     * @return the primary key of this cliente
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this cliente.
     *
     * @param primaryKey the primary key of this cliente
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the id cliente of this cliente.
     *
     * @return the id cliente of this cliente
     */
    public long getIdCliente();

    /**
     * Sets the id cliente of this cliente.
     *
     * @param idCliente the id cliente of this cliente
     */
    public void setIdCliente(long idCliente);

    /**
     * Returns the activado of this cliente.
     *
     * @return the activado of this cliente
     */
    public int getActivado();

    /**
     * Sets the activado of this cliente.
     *
     * @param activado the activado of this cliente
     */
    public void setActivado(int activado);

    /**
     * Returns the denegado of this cliente.
     *
     * @return the denegado of this cliente
     */
    public int getDenegado();

    /**
     * Sets the denegado of this cliente.
     *
     * @param denegado the denegado of this cliente
     */
    public void setDenegado(int denegado);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.proyecto.clientes.model.Cliente cliente);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.proyecto.clientes.model.Cliente> toCacheModel();

    @Override
    public com.proyecto.clientes.model.Cliente toEscapedModel();

    @Override
    public com.proyecto.clientes.model.Cliente toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
