package com.proyecto.citas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Cita service. Represents a row in the &quot;RES_CITA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.proyecto.citas.model.impl.CitaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.proyecto.citas.model.impl.CitaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Cita
 * @see com.proyecto.citas.model.impl.CitaImpl
 * @see com.proyecto.citas.model.impl.CitaModelImpl
 * @generated
 */
public interface CitaModel extends BaseModel<Cita> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a cita model instance should use the {@link Cita} interface instead.
     */

    /**
     * Returns the primary key of this cita.
     *
     * @return the primary key of this cita
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this cita.
     *
     * @param primaryKey the primary key of this cita
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the id cita of this cita.
     *
     * @return the id cita of this cita
     */
    public int getIdCita();

    /**
     * Sets the id cita of this cita.
     *
     * @param idCita the id cita of this cita
     */
    public void setIdCita(int idCita);

    /**
     * Returns the id cliente of this cita.
     *
     * @return the id cliente of this cita
     */
    public int getIdCliente();

    /**
     * Sets the id cliente of this cita.
     *
     * @param idCliente the id cliente of this cita
     */
    public void setIdCliente(int idCliente);

    /**
     * Returns the fecha cita of this cita.
     *
     * @return the fecha cita of this cita
     */
    public Date getFechaCita();

    /**
     * Sets the fecha cita of this cita.
     *
     * @param fechaCita the fecha cita of this cita
     */
    public void setFechaCita(Date fechaCita);

    /**
     * Returns the descripcion of this cita.
     *
     * @return the descripcion of this cita
     */
    @AutoEscape
    public String getDescripcion();

    /**
     * Sets the descripcion of this cita.
     *
     * @param descripcion the descripcion of this cita
     */
    public void setDescripcion(String descripcion);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.proyecto.citas.model.Cita cita);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.proyecto.citas.model.Cita> toCacheModel();

    @Override
    public com.proyecto.citas.model.Cita toEscapedModel();

    @Override
    public com.proyecto.citas.model.Cita toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
