package com.proyecto.citas.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DiaFestivo service. Represents a row in the &quot;RES_DIA_FESTIVO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.proyecto.citas.model.impl.DiaFestivoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.proyecto.citas.model.impl.DiaFestivoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiaFestivo
 * @see com.proyecto.citas.model.impl.DiaFestivoImpl
 * @see com.proyecto.citas.model.impl.DiaFestivoModelImpl
 * @generated
 */
public interface DiaFestivoModel extends BaseModel<DiaFestivo> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a dia festivo model instance should use the {@link DiaFestivo} interface instead.
     */

    /**
     * Returns the primary key of this dia festivo.
     *
     * @return the primary key of this dia festivo
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this dia festivo.
     *
     * @param primaryKey the primary key of this dia festivo
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the id festivo of this dia festivo.
     *
     * @return the id festivo of this dia festivo
     */
    public int getIdFestivo();

    /**
     * Sets the id festivo of this dia festivo.
     *
     * @param idFestivo the id festivo of this dia festivo
     */
    public void setIdFestivo(int idFestivo);

    /**
     * Returns the fecha festivo of this dia festivo.
     *
     * @return the fecha festivo of this dia festivo
     */
    public Date getFechaFestivo();

    /**
     * Sets the fecha festivo of this dia festivo.
     *
     * @param fechaFestivo the fecha festivo of this dia festivo
     */
    public void setFechaFestivo(Date fechaFestivo);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.proyecto.citas.model.DiaFestivo diaFestivo);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.proyecto.citas.model.DiaFestivo> toCacheModel();

    @Override
    public com.proyecto.citas.model.DiaFestivo toEscapedModel();

    @Override
    public com.proyecto.citas.model.DiaFestivo toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
