package com.proyecto.citas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DiaLibre service. Represents a row in the &quot;RES_DIA_LIBRE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.proyecto.citas.model.impl.DiaLibreModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.proyecto.citas.model.impl.DiaLibreImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiaLibre
 * @see com.proyecto.citas.model.impl.DiaLibreImpl
 * @see com.proyecto.citas.model.impl.DiaLibreModelImpl
 * @generated
 */
public interface DiaLibreModel extends BaseModel<DiaLibre> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a dia libre model instance should use the {@link DiaLibre} interface instead.
     */

    /**
     * Returns the primary key of this dia libre.
     *
     * @return the primary key of this dia libre
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this dia libre.
     *
     * @param primaryKey the primary key of this dia libre
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the id libre of this dia libre.
     *
     * @return the id libre of this dia libre
     */
    public int getIdLibre();

    /**
     * Sets the id libre of this dia libre.
     *
     * @param idLibre the id libre of this dia libre
     */
    public void setIdLibre(int idLibre);

    /**
     * Returns the dia of this dia libre.
     *
     * @return the dia of this dia libre
     */
    @AutoEscape
    public String getDia();

    /**
     * Sets the dia of this dia libre.
     *
     * @param dia the dia of this dia libre
     */
    public void setDia(String dia);

    /**
     * Returns the libre of this dia libre.
     *
     * @return the libre of this dia libre
     */
    public int getLibre();

    /**
     * Sets the libre of this dia libre.
     *
     * @param libre the libre of this dia libre
     */
    public void setLibre(int libre);

    /**
     * Returns the codigo dia of this dia libre.
     *
     * @return the codigo dia of this dia libre
     */
    @AutoEscape
    public String getCodigoDia();

    /**
     * Sets the codigo dia of this dia libre.
     *
     * @param codigoDia the codigo dia of this dia libre
     */
    public void setCodigoDia(String codigoDia);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.proyecto.citas.model.DiaLibre diaLibre);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.proyecto.citas.model.DiaLibre> toCacheModel();

    @Override
    public com.proyecto.citas.model.DiaLibre toEscapedModel();

    @Override
    public com.proyecto.citas.model.DiaLibre toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
