package com.proyecto.citas.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DiasFestivos service. Represents a row in the &quot;RES_DIAS_FESTIVOS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.proyecto.citas.model.impl.DiasFestivosModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.proyecto.citas.model.impl.DiasFestivosImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiasFestivos
 * @see com.proyecto.citas.model.impl.DiasFestivosImpl
 * @see com.proyecto.citas.model.impl.DiasFestivosModelImpl
 * @generated
 */
public interface DiasFestivosModel extends BaseModel<DiasFestivos> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a dias festivos model instance should use the {@link DiasFestivos} interface instead.
     */

    /**
     * Returns the primary key of this dias festivos.
     *
     * @return the primary key of this dias festivos
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this dias festivos.
     *
     * @param primaryKey the primary key of this dias festivos
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the id festivo of this dias festivos.
     *
     * @return the id festivo of this dias festivos
     */
    public int getIdFestivo();

    /**
     * Sets the id festivo of this dias festivos.
     *
     * @param idFestivo the id festivo of this dias festivos
     */
    public void setIdFestivo(int idFestivo);

    /**
     * Returns the fecha festivo of this dias festivos.
     *
     * @return the fecha festivo of this dias festivos
     */
    public Date getFechaFestivo();

    /**
     * Sets the fecha festivo of this dias festivos.
     *
     * @param fechaFestivo the fecha festivo of this dias festivos
     */
    public void setFechaFestivo(Date fechaFestivo);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.proyecto.citas.model.DiasFestivos diasFestivos);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.proyecto.citas.model.DiasFestivos> toCacheModel();

    @Override
    public com.proyecto.citas.model.DiasFestivos toEscapedModel();

    @Override
    public com.proyecto.citas.model.DiasFestivos toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
