package com.proyecto.citas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DiasLibres service. Represents a row in the &quot;RES_DIAS_LIBRES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.proyecto.citas.model.impl.DiasLibresModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.proyecto.citas.model.impl.DiasLibresImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiasLibres
 * @see com.proyecto.citas.model.impl.DiasLibresImpl
 * @see com.proyecto.citas.model.impl.DiasLibresModelImpl
 * @generated
 */
public interface DiasLibresModel extends BaseModel<DiasLibres> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a dias libres model instance should use the {@link DiasLibres} interface instead.
     */

    /**
     * Returns the primary key of this dias libres.
     *
     * @return the primary key of this dias libres
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this dias libres.
     *
     * @param primaryKey the primary key of this dias libres
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the dia of this dias libres.
     *
     * @return the dia of this dias libres
     */
    @AutoEscape
    public String getDia();

    /**
     * Sets the dia of this dias libres.
     *
     * @param dia the dia of this dias libres
     */
    public void setDia(String dia);

    /**
     * Returns the libre of this dias libres.
     *
     * @return the libre of this dias libres
     */
    public int getLibre();

    /**
     * Sets the libre of this dias libres.
     *
     * @param libre the libre of this dias libres
     */
    public void setLibre(int libre);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.proyecto.citas.model.DiasLibres diasLibres);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.proyecto.citas.model.DiasLibres> toCacheModel();

    @Override
    public com.proyecto.citas.model.DiasLibres toEscapedModel();

    @Override
    public com.proyecto.citas.model.DiasLibres toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
