package com.proyecto.citas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the HorarioTrabajo service. Represents a row in the &quot;RES_HORARIO_TRABAJO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.proyecto.citas.model.impl.HorarioTrabajoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.proyecto.citas.model.impl.HorarioTrabajoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HorarioTrabajo
 * @see com.proyecto.citas.model.impl.HorarioTrabajoImpl
 * @see com.proyecto.citas.model.impl.HorarioTrabajoModelImpl
 * @generated
 */
public interface HorarioTrabajoModel extends BaseModel<HorarioTrabajo> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a horario trabajo model instance should use the {@link HorarioTrabajo} interface instead.
     */

    /**
     * Returns the primary key of this horario trabajo.
     *
     * @return the primary key of this horario trabajo
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this horario trabajo.
     *
     * @param primaryKey the primary key of this horario trabajo
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the id horario of this horario trabajo.
     *
     * @return the id horario of this horario trabajo
     */
    public int getIdHorario();

    /**
     * Sets the id horario of this horario trabajo.
     *
     * @param idHorario the id horario of this horario trabajo
     */
    public void setIdHorario(int idHorario);

    /**
     * Returns the hora inicio of this horario trabajo.
     *
     * @return the hora inicio of this horario trabajo
     */
    @AutoEscape
    public String getHoraInicio();

    /**
     * Sets the hora inicio of this horario trabajo.
     *
     * @param horaInicio the hora inicio of this horario trabajo
     */
    public void setHoraInicio(String horaInicio);

    /**
     * Returns the hora fin of this horario trabajo.
     *
     * @return the hora fin of this horario trabajo
     */
    @AutoEscape
    public String getHoraFin();

    /**
     * Sets the hora fin of this horario trabajo.
     *
     * @param horaFin the hora fin of this horario trabajo
     */
    public void setHoraFin(String horaFin);

    /**
     * Returns the hora inicio tarde of this horario trabajo.
     *
     * @return the hora inicio tarde of this horario trabajo
     */
    @AutoEscape
    public String getHoraInicioTarde();

    /**
     * Sets the hora inicio tarde of this horario trabajo.
     *
     * @param horaInicioTarde the hora inicio tarde of this horario trabajo
     */
    public void setHoraInicioTarde(String horaInicioTarde);

    /**
     * Returns the hora fin tarde of this horario trabajo.
     *
     * @return the hora fin tarde of this horario trabajo
     */
    @AutoEscape
    public String getHoraFinTarde();

    /**
     * Sets the hora fin tarde of this horario trabajo.
     *
     * @param horaFinTarde the hora fin tarde of this horario trabajo
     */
    public void setHoraFinTarde(String horaFinTarde);

    /**
     * Returns the duracion citas of this horario trabajo.
     *
     * @return the duracion citas of this horario trabajo
     */
    public int getDuracionCitas();

    /**
     * Sets the duracion citas of this horario trabajo.
     *
     * @param duracionCitas the duracion citas of this horario trabajo
     */
    public void setDuracionCitas(int duracionCitas);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.proyecto.citas.model.HorarioTrabajo horarioTrabajo);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.proyecto.citas.model.HorarioTrabajo> toCacheModel();

    @Override
    public com.proyecto.citas.model.HorarioTrabajo toEscapedModel();

    @Override
    public com.proyecto.citas.model.HorarioTrabajo toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
